package former;

import java.awt.Graphics;
import java.awt.Color;
import java.util.ArrayList;

public class Random_former_JPanel extends javax.swing.JPanel {
private static ArrayList<Forms> geomatri = new ArrayList<>();
private int RandomForm;
int Formchoice = 1;  
File_manage_forms list = new File_manage_forms();

    /**
     * Creates new form Random_former_JPanel
     */
    public Random_former_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Rensa = new javax.swing.JButton();
        Cirkelknapp = new javax.swing.JRadioButton();
        Triangelknapp = new javax.swing.JRadioButton();
        Rektangelknapp = new javax.swing.JRadioButton();
        Save = new javax.swing.JButton();
        paste = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Rensa.setText("Rensa");
        Rensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RensaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cirkelknapp);
        Cirkelknapp.setSelected(true);
        Cirkelknapp.setText("Cirkel");
        Cirkelknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirkelknappActionPerformed(evt);
            }
        });

        buttonGroup1.add(Triangelknapp);
        Triangelknapp.setText("Triangel");
        Triangelknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangelknappActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rektangelknapp);
        Rektangelknapp.setText("Rektangel");
        Rektangelknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RektangelknappActionPerformed(evt);
            }
        });

        Save.setText("Spara");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        paste.setText("Hämta");
        paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Cirkelknapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Triangelknapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rektangelknapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Triangelknapp)
                    .addComponent(Cirkelknapp)
                    .addComponent(Rektangelknapp)
                    .addComponent(Rensa)
                    .addComponent(Save)
                    .addComponent(paste))
                .addGap(450, 450, 450))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RensaActionPerformed
   geomatri = new ArrayList<>();
                repaint();

        
    }//GEN-LAST:event_RensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
 int x = evt.getX();
        int y = evt.getY();
        switch (Formchoice){
        case 1:
    int RandomX = (int) (Math.random()*281);
        int RandomY = (int) (Math.random()*251);
        int RandomRadie =(int)(Math.random()*151);
        Forms c = new Cirkel(x,y, RandomRadie, true);
        geomatri.add(c);
        repaint();
        break;
        
        case 2:
        RandomX = (int) (Math.random()*281);
        RandomY = (int) (Math.random()*251);
        int RandomBas =(int)(Math.random()*151);
        int RandomHöjd =(int)(Math.random()*151);
        Forms t = new Triangel(x,y,RandomBas,RandomHöjd,  true);
        geomatri.add(t);
        repaint();
        break;
        
        case 3:
        RandomX = (int) (Math.random()*281);
        RandomY = (int) (Math.random()*251);
        RandomBas =(int)(Math.random()*151);
        RandomHöjd =(int)(Math.random()*151);
        Forms r = new Rektangel(x,y,RandomBas,RandomHöjd,  true);
        geomatri.add(r);
        repaint();
        break;

    }           
    }//GEN-LAST:event_formMouseClicked

    private void CirkelknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirkelknappActionPerformed
        Formchoice = 1;
    }//GEN-LAST:event_CirkelknappActionPerformed

    private void TriangelknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangelknappActionPerformed
        Formchoice = 2;
    }//GEN-LAST:event_TriangelknappActionPerformed

    private void RektangelknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RektangelknappActionPerformed
        Formchoice = 3;
    }//GEN-LAST:event_RektangelknappActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
    list.saveToFile(geomatri);
    
    }//GEN-LAST:event_SaveActionPerformed

    private void pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteActionPerformed
    geomatri=list.readfromfile();
    repaint();
    }//GEN-LAST:event_pasteActionPerformed
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for(int i=0; i<geomatri.size(); i++){
         geomatri.get(i).draw(g);
        }
        
       
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cirkelknapp;
    private javax.swing.JRadioButton Rektangelknapp;
    private javax.swing.JButton Rensa;
    private javax.swing.JButton Save;
    private javax.swing.JRadioButton Triangelknapp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton paste;
    // End of variables declaration//GEN-END:variables
}
